### ISSUE TITLE
Does jSmart support include and extends? 

### ISSUE THREAD

**Issue by AceMood** [umakantp/jsmart#13]
It seems that getTemplate method always return throwing an error.

**Comment by iancj** [comment]
Yes, I also met the same problem.How can I fix this ?

**Comment by umakantp** [comment]
Can you share your code please?

**Comment by akshay-since1987** [comment]
I think this issue arises because we try to give path relative to the current template while jSmart expects it to be relative to the project. I fixed it by using the code below to over-ride the default include method
>>
jSmart.prototype.registerPlugin(
                'function', 
                'include', 
                function(params, data)
                {
                    var contents = "";
                    if(path.isAbsolute(params["file"])) {
                        contents = fs.readFileSync(params['file']);
                    } else {
                        var dirName = path.dirname(file);   // This is the path of the current template inside the root directory of my project
                        var filePath = path.resolve(dirName, params["file"]);
                        contents = fs.readFileSync(filePath, {encoding: 'utf-8'});
                    }
                    return contents;
                }
            );
I could do this since I had a very simple Project structure where src/templates/pages contained the current template and src/templates/components contained the template to be included

**Comment by Avcajaraville** [comment]
Im also having this problem, any idea where to go ?

**Comment by umakantp** [comment]
This has been fixed in  the release v2.15.1
